Gmail Login Page
AKD-2024/assignment1 pull request #1
Opened 2024-07-06 17:24 UTC by AKD-2024

Create index.html, style.css, and assets folder for google logo and update README.md file.

2024-07-09 12:35 UTC, PurnimaCompro requested changes

2024-07-09 12:35 UTC, PurnimaCompro commented on style.css
> +
css should not be applied on selector

2024-07-09 17:00 UTC, AKD-2024 commented on index.html
> +</html>
@PurnimaCompro Ma'am, what is the git error?

2024-07-09 17:02 UTC, AKD-2024 commented on style.css
> +
@PurnimaCompro I think you meant directly on the tag, I know but only single img tag was used so it was not going to affect anywhere that is why I did this. Although resolved!

2024-07-09 17:04 UTC, AKD-2024 commented on style.css
> +}
@PurnimaCompro Ma'am, there are three selectors in CSS, I can't apply styles to id and tags. So I am left with class only.  Also resolved!

2024-07-10 07:26 UTC, PurnimaCompro approved these changes

2024-07-10 07:35 UTC, merged